# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: "dataUpdate"

on:
  schedule:
    - cron: '27 * * * *' # ñàéû13ï™Ç…é¿çs

jobs:
  build:
    runs-on: ubuntu-latest
    environment: update
    steps:
      - uses: actions/checkout@v2

      - name: Update Data
        run: sh ./script/update.sh

      - name: Set up Git
        run: |
          git config --local user.email "${{ secrets.GIT_EMAIL }}"
          git config --local user.name "sby-h-takeshima"

      - name: Commit & Push changes
        run: |
          git add .
          git diff --cached --quiet || git commit -m "Automated update $(date '+%Y%m%d%H%M')"
          git push origin master
