# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Auto Commit and Push

on:
  schedule:
    - cron: '48 * * * *' # 毎日0時（UTC）に実行
  workflow_dispatch: # 手動実行も可能

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # プッシュ権限を付与
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make changes
        run: |
          echo "Updated on $(date)" > update.txt

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Auto-update file"
          git push
